Repository depromeet/jalingobi-server, pull requests merged in 2023-06, with the labels that each got.

#42 [Bug] Codecov PR 시 comment 생성되지 않는 문제 해결
  codecov.yml
Labels: 🐞 BugFix

#50 [Refactor] Mapper 사용 및 메서드 리팩토링
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/response/KakaoAuthResponse.java
  Module-API/src/main/java/depromeet/api/domain/auth/mapper/AuthMapper.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/KakaoAuthUseCase.java
  Module-API/src/main/java/depromeet/api/domain/auth/validator/OAuthValidator.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
  Module-Domain/src/main/java/depromeet/domain/user/adaptor/UserAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Social.java
  Module-Domain/src/main/java/depromeet/domain/user/service/UserService.java
Labels: 🔨 Refactor

#52 [Feature] 챌린지, 규칙의 도메인, DTO, mapper 생성
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Category.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Duration.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/Rule.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#59 [Test] 소셜로그인 도메인 테스트 코드 작성
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/user/adaptor/UserAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/user/exception/AccountAlreadyExist.java
  Module-Domain/src/main/java/depromeet/domain/user/exception/DuplicatedEmailException.java
  Module-Domain/src/main/java/depromeet/domain/user/service/UserService.java
  Module-Domain/src/test/java/depromeet/domain/user/adaptor/UserAdaptorTest.java
  Module-Domain/src/test/java/depromeet/domain/user/service/UserServiceTest.java
Labels: ✅ Test

#61 [Feature] 챌린지 생성 추가
  Module-API/build.gradle
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/rule/mapper/RuleMapper.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/adaptor/ChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Duration.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeRepository.java
  Module-Domain/src/main/java/depromeet/domain/rule/adaptor/RuleAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/Rule.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/Rules.java
  Module-Domain/src/main/java/depromeet/domain/rule/repository/RuleRepository.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#62 [Refactor] 소셜로그인 응답 형식 변경
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/response/KakaoAuthResponse.java
  Module-API/src/main/java/depromeet/api/domain/auth/mapper/AuthMapper.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/KakaoAuthUseCase.java
  Module-API/src/main/java/depromeet/api/util/CookieUtil.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
Labels: 🔨 Refactor

#66 [Fix] JWT 인증, 인가 해결
  Module-API/src/main/java/depromeet/api/config/security/CustomUserDetails.java
  Module-API/src/main/java/depromeet/api/config/security/filter/JwtRequestFilter.java
  Module-API/src/main/java/depromeet/api/util/AuthenticationUtil.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Role.java
Labels: 🐞 BugFix, 🙋‍♀️ 유저

#69 [Refactor] ResponseService내의 메서드를 static method로 변경
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/image/controller/ImageController.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionHandler.java
  Module-Common/src/main/java/depromeet/common/response/ResponseService.java
Labels: 🔨 Refactor

#70 [Feature] 소셜로그인 유효성 검증 및 예외 처리
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/request/KakaoAuthRequest.java
  Module-API/src/main/java/depromeet/api/domain/auth/validator/OAuthValidator.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionHandler.java
  Module-Common/src/main/java/depromeet/common/response/ResponseService.java
Labels: ✨ Feature, 🙋‍♀️ 유저

#71 [Refactor] reissue API에서 토큰을 보내는 방법 수정
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/AuthUseCase.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
Labels: 🔨 Refactor, 🙋‍♀️ 유저

#75 [Feature] 챌린지 지출 기록 테스트 코드 작성 및 API 문서 작성
  Module-API/src/main/java/depromeet/api/config/SwaggerConfig.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/CreateRecordResponse.java
  Module-API/src/test/java/depromeet/api/controller/RecordControllerTest.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
  Module-Domain/src/test/java/depromeet/domain/record/domain/RecordEvaluationTest.java
Labels: 📃 Docs, ✅ Test

#79 [Test] 카카오 소셜로그인 테스트 코드 추가
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/request/KakaoAuthRequest.java
  Module-API/src/main/java/depromeet/api/domain/auth/feign/dto/Keys.java
  Module-API/src/main/java/depromeet/api/domain/auth/feign/dto/UserInfo.java
  Module-API/src/main/java/depromeet/api/domain/auth/feign/kakaoApiFeignClient.java
  Module-API/src/main/java/depromeet/api/domain/auth/feign/kakaoAuthFeignClient.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/KakaoAuthUseCase.java
  Module-API/src/main/java/depromeet/api/domain/auth/validator/OAuthValidator.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
  Module-Domain/src/test/java/depromeet/domain/user/domain/UserTest.java
Labels: ✅ Test

#73 [Refactor] AuthUseCase를 RefreshTokenUseCase로 변경
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/RefreshTokenUseCase.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
Labels: 🔨 Refactor

#80 [Docs] 소셜로그인 API 문서 작성
  Module-API/build.gradle
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
Labels: 📃 Docs

#81 [Refactor] 챌린지와 챌린지 규칙을 양방향 연관관계로 맺기
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/rule/mapper/ChallengeRuleMapper.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/rule/adaptor/ChallengeRuleAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/rule/adaptor/RuleAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/ChallengeRule.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/Rules.java
  Module-Domain/src/main/java/depromeet/domain/rule/repository/ChallengeRuleRepository.java
  Module-Domain/src/main/java/depromeet/domain/rule/repository/RuleRepository.java
Labels: 🔨 Refactor, 🕵️ 챌린지 탐색

#77 [Refactor] 챌린지 기록 예외 처리 추가 및 리팩토링
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/validator/RecordValidator.java
  Module-API/src/test/java/depromeet/api/domain/record/validator/RecordValidatorTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/adaptor/ChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/ChallengeNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Evaluation.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
  Module-Domain/src/test/java/depromeet/domain/record/domain/RecordEvaluationTest.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#90 [Test, Docs] image upload 테스트 코드 작성 및 API 문서 작성
  Module-API/src/main/java/depromeet/api/domain/image/controller/ImageController.java
  Module-API/src/main/java/depromeet/api/domain/image/dto/request/IssuePresignedUrlRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/validator/RecordValidator.java
  Module-API/src/test/java/depromeet/api/controller/ImageControllerTest.java
Labels: 📃 Docs, ✅ Test

#88 [Feature] 유저 챌린지 테이블 추가
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/UserChallenge.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
Labels: ✨ Feature, 🙋‍♀️ 유저, 🕵️ 챌린지 탐색

#92 [Feature] JPAQueryFactory Bean 등록
  Module-Domain/src/main/java/depromeet/domain/config/JpaConfig.java
Labels: ✨ Feature

#95 [Feature] 챌린지 기록 수정
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/exception/InvalidUserRecordException.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/validator/RecordValidator.java
  Module-API/src/test/java/depromeet/api/controller/RecordControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/validator/RecordValidatorTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/record/adaptor/RecordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/main/java/depromeet/domain/record/exception/RecordNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
Labels: ✨ Feature, ✍️ 챌린지 기록

#104 [Docs] 챌린지 피드 및 지출 상세보기 API 문서 수정
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/Feed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/ChallengeRecord.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/RecordComment.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
Labels: 📃 Docs

#107 API 문서 최신화
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/Feed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/ChallengeRecord.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/RecordComment.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
Labels: 🌏 Deploy

#105 [Refactor] keyword 테이블 생성
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/keyword/dto/KeywordsDto.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/keyword/ChallengeKeyword.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/keyword/ChallengeKeywords.java
  Module-Domain/src/main/java/depromeet/domain/keyword/adaptor/KeywordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/keyword/domain/Keyword.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/AllKeywordLengthIsOverException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/CannotAddKeywordException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/KeywordFormatException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/repository/KeywordRepository.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
Labels: 🔨 Refactor, 🕵️ 챌린지 탐색

#108 [feature] comment 도메인 생성
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comments.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
Labels: ✨ Feature, ✍️ 챌린지 기록

#112 [Feature] 챌린지 수정 API 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ChallengeCategories.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/ChallengeNotBelongToUserException.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/ChallengeRule.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#111 [Docs] API 수정 및 세분화에 따른 문서 수정
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/Feed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeProceedingInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeProceedingInfoUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyChallengeListUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  docker-compose.yml
Labels: 📃 Docs, 🗒️ 챌린지 피드

#115 API 문서 최신화
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/Feed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeProceedingInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeProceedingInfoUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyChallengeListUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/keyword/dto/KeywordsDto.java
  Module-API/src/test/java/depromeet/api/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ChallengeCategories.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/keyword/ChallengeKeyword.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/keyword/ChallengeKeywords.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/ChallengeNotBelongToUserException.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comments.java
  Module-Domain/src/main/java/depromeet/domain/keyword/adaptor/KeywordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/keyword/domain/Keyword.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/AllKeywordLengthIsOverException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/CannotAddKeywordException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/exception/KeywordFormatException.java
  Module-Domain/src/main/java/depromeet/domain/keyword/repository/KeywordRepository.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/ChallengeRule.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
  docker-compose.yml
Labels: 🌏 Deploy

#116 [Feature] 게스트 모드 추가
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/request/GetChallengeRoomRequest.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/request/GetMyFeedRequest.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeRoomResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeRoomUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomUseCase.java
  Module-API/src/main/java/depromeet/api/domain/guest/controller/GuestController.java
  Module-API/src/main/java/depromeet/api/domain/guest/dto/ExperienceGuestModeResponse.java
  Module-API/src/main/java/depromeet/api/domain/guest/mapper/GuestMapper.java
  Module-API/src/main/java/depromeet/api/domain/guest/usecase/ExperienceGuestModeUseCase.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
  Module-API/src/test/java/depromeet/api/HelloControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/auth/controller/AuthControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/guest/controller/GuestControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/image/controller/ImageControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Platform.java
Labels: ✨ Feature, 🙋‍♀️ 유저

#117 [Feature] 챌린지 삭제 구현
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/DeleteChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/adaptor/ChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/ChallengeCannotBeDeletedAfterStartException.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#119 [Refactor] CreateChallengeRequest에서 challengeRule 필드의 타입 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/rule/mapper/ChallengeRuleMapper.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/rule/domain/ChallengeRule.java
Labels: 🔨 Refactor

#122 [Docs] 내 방 피드 API 명세 수정
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
Labels: 📃 Docs, 🗒️ 챌린지 피드

#123 [Docs] 챌린지 생성, 수정, 삭제 API 문서 작성
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
Labels: 📃 Docs

#124 [Feature] 시작된 챌린지는 수정할 수 없는 조건 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/DeleteChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/ChallengeCannotBeUpdatedAfterStartException.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#125 [Feature] 마이페이지 프로필 수정
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/request/UpdateProfileRequest.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/UpdateProfileUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Profile.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
Labels: ✨ Feature, 🤠 마이페이지

#130 [Refactor] 챌린지 생성, 수정 요청 DTO 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
Labels: 🔨 Refactor

#132 [Feature] 회원 로그아웃 구현
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/LogoutUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
Labels: ✨ Feature, 🤠 마이페이지

#135 [Feature] 이모지 생성
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/request/CreateEmojiRequest.java
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/response/CreateEmojiResponse.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/CreateEmojiUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/Emoji.java
  Module-Domain/src/main/java/depromeet/domain/emoji/exception/DuplicatedEmojiException.java
  Module-Domain/src/main/java/depromeet/domain/emoji/exception/EmojiNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Emoji.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/adaptor/UserChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Emojis.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/UnparticipatedChallengeUserException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/repository/UserChallengeRepository.java
Labels: ✨ Feature, ✅ Test, ✍️ 챌린지 기록

#137 [Feature] 챌린지 피드 1차 작업
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/CreateEmojiUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/controller/SubscribeChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/controller/SubscribeController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeProgress.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeProceedingInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/mapper/RecordListMapper.java
  Module-API/src/main/java/depromeet/api/domain/feed/mapper/UserChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeProceedingInfoUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyChallengeListUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/exception/InvalidUserChallengeException.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/Emoji.java
  Module-Domain/src/main/java/depromeet/domain/record/adaptor/RecordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepository.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/adaptor/UserChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/ProgressInfoNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/UnparticipatedChallengeUserException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/UserNotParticipatedInChallengeException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/repository/UserChallengeCustomRepository.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/repository/UserChallengeCustomRepositoryImpl.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/repository/UserChallengeRepository.java
Labels: ✨ Feature, 🗒️ 챌린지 피드

#140 [Feature] 챌린지 참가
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/userchallenge/dto/request/CreateUserChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/userchallenge/usecase/CreateUserChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/adaptor/UserChallengeAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Status.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/ChallengeIsFullException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/ChallengeIsStartedException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/DuplicateParticipationException.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/StatusNotFoundException.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#141 [Feature] 마이페이지 조회 구현
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetMyPageResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/mapper/MyPageMapper.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetMyPageUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Status.java
Labels: ✨ Feature, 🤠 마이페이지

#143 [Refactor] user_challenge와 challenge_record 연관관계 추가
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#150 [Refactor] 클래스 위치 및 패키지 구조 리팩토링
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/JoinChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/emoji/controller/EmojiController.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/emoji/controller/EmojiControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
Labels: 🔨 Refactor

#146 [Feature] 마이페이지 User Challenge 전체 조회
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetUserChallengesResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/mapper/MyPageMapper.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetUserChallengesUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
Labels: ✨ Feature, 🤠 마이페이지

#151 [Feature] 내 방 피드 데이터 추가 및 리팩토링
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/RecordInfo.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/EmojiType.java
Labels: ✨ Feature, 🗒️ 챌린지 피드

#159 API 문서 최신화
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/FeedRecordInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeProceedingInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/RecordInfo.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
  Module-API/src/test/java/depromeet/api/domain/feed/controller/FeedControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/feed/usecase/GetMyChallengeListUseCaseTest.java
  Module-Domain/src/main/java/depromeet/domain/record/adaptor/RecordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepository.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
Labels: 🌏 Deploy

#163 [Feature] 카테고리 Enum 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-Domain/src/main/java/depromeet/domain/category/adaptor/CategoryAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Category.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/CategoryType.java
Labels: ✨ Feature

#165 [Feature] 댓글 생성
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/CreateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/CreateCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/mapper/CommentMapper.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/CreateCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/comment/repository/CommentRepository.java
Labels: ✨ Feature, ✅ Test, ✍️ 챌린지 기록

#161 [Refactor] 마이페이지 조회 응답 값 추가
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetMyPageResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/mapper/MyPageMapper.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetMyPageUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
Labels: 🔨 Refactor, 🤠 마이페이지

#167 [Feature] 댓글 수정
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/UpdateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/CreateCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/UpdateCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/comment/exception/CommentNotBelongToUserException.java
  Module-Domain/src/main/java/depromeet/domain/comment/exception/CommentNotFoundException.java
Labels: ✨ Feature, ✅ Test, ✍️ 챌린지 기록

#172 [Feature] 댓글 삭제
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
Labels: ✨ Feature, ✅ Test, ✍️ 챌린지 기록

#174 [Refactor] 챌린지 기록 endpoint 수정 및 유저 Profile name 칼럼 명 변경
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Profile.java
  Module-Domain/src/test/java/depromeet/domain/user/domain/UserTest.java
Labels: 🔨 Refactor

#179 [Feature] 자린고비 시스템 설계
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/domain/Jalingobi.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/domain/Level.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/domain/SmallTalk.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/exception/LevelNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/test/java/depromeet/domain/jalingobi/domain/LevelTest.java
  Module-Domain/src/test/java/depromeet/domain/user/domain/UserTest.java
Labels: ✨ Feature, 🐟 자린고비

#187 [Feature] 마이페이지 레벨 별 자린고비 프로필 조회 구현
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetJalingobiImgResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/mapper/MyPageMapper.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetJalingobiImgUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/adaptor/JalingobiAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/exception/JalingobiNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/repository/JalingobiRepository.java
Labels: ✨ Feature, 🤠 마이페이지

#188 [Docs] 댓글 API 문서 작성
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/CreateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/UpdateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/CreateCommentResponse.java
Labels: 📃 Docs

#190 [Feature] 자린고비 홈 조회 구현
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/controller/JalingobiController.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/dto/response/GetJalingobiResponse.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/mapper/JalingobiMapper.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/usecase/GetJalingobiUseCase.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/adaptor/JalingobiAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/domain/Jalingobi.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
Labels: ✨ Feature, 🐟 자린고비

#200 [Feature] 랜덤 닉네임 생성
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateRandomNicknameResponse.java
  Module-API/src/main/java/depromeet/api/util/RandomNicknameGenerator.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/NicknameType.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#206 [Feature] Cors 설정 추가
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
Labels: ✨ Feature

#211 [Bug] sql 파일의 table name 소문자로 변경
  Module-Domain/src/main/resources/sql/category.sql
  Module-Domain/src/main/resources/sql/jalingobi.sql
  Module-Domain/src/main/resources/sql/small_talk.sql
Labels: 🐞 BugFix

#212 [Bug] sql 파일의 table name 소문자로 변경
  Module-Domain/src/main/resources/sql/category.sql
  Module-Domain/src/main/resources/sql/jalingobi.sql
  Module-Domain/src/main/resources/sql/small_talk.sql
Labels: 🐞 BugFix

#204 [Feature] 챌린지 상세 조회
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/DateInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/HeadCountResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/ProfileResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/GetChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ChallengeCategories.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#214 [Refactor] category.sql에서 오타 수정
  Module-Domain/src/main/resources/sql/category.sql
Labels: 🔨 Refactor

#216 [Refactor] 랜덤 닉네임 URI 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
Labels: 🔨 Refactor

#217 [Feature] 챌린지 가입 시 유저 프로필 이미지도 저장
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/JoinChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#222 [Feature] 자린고비 한마디 조회 구현
  Module-API/src/main/java/depromeet/api/domain/jalingobi/controller/JalingobiController.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/dto/request/GetSmallTalkRequest.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/dto/response/GetSmallTalkResponse.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/mapper/JalingobiMapper.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/usecase/GetSmallTalkUseCase.java
  Module-API/src/main/java/depromeet/api/util/AuthenticationUtil.java
  Module-API/src/main/java/depromeet/api/util/RandomUtil.java
  Module-API/src/main/java/depromeet/api/util/exception/ListNotNullException.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/adaptor/JalingobiAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/adaptor/SmallTalkAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/exception/SmallTalkNotFoundException.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/repository/SmallTalkRepository.java
  Module-Domain/src/main/java/depromeet/domain/user/util/ImageUrlUtil.java
Labels: ✨ Feature, 🐟 자린고비

#223 [Feature] 챌린지의 상태를 알 수 있는 로직 구현
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/StatusType.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#224 [Bug] 자린고비 홈 조회 에러 해결
  Module-API/src/main/java/depromeet/api/domain/jalingobi/dto/JalingobiInfo.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/dto/response/GetJalingobiResponse.java
  Module-Domain/src/main/java/depromeet/domain/jalingobi/domain/Level.java
Labels: 🐞 BugFix, 🐟 자린고비

#229 [Refactor] 사용자가 참여한 챌린지 조회 반환 값 DTO로 리팩토링
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/DateInfo.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetMyPageResponse.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
Labels: 🔨 Refactor, 🤠 마이페이지

#231 [Refactor] UserChallenge에 있는 currentCharge 필드에 기본값 설정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/JoinChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: 🔨 Refactor

#232 [Feature] 챌린지 생성자는 기본 프로필로 해당 챌린지에 참여
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#234 [Refactor] 챌린지 기록 응답 값, 기록 생성, 삭제, 수정 시 currentCharge 값 변경
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/UpdateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/CreateRecordResponse.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/DeleteRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/exception/NegativeChargeException.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#237 [Feature] challenge와 user 간에 1:1 매핑
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
Labels: ✨ Feature, ✅ Test, 🙋‍♀️ 유저, 🕵️ 챌린지 탐색

#238 [Refactor] 지출 기록 상세보기 API 리팩토링
  Module-API/src/main/java/depromeet/api/domain/record/usecase/GetRecordUseCase.java
Labels: 🔨 Refactor, 🗒️ 챌린지 피드

#236 [Refactor] 피드 관련 API 리팩토링
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/request/GetChallengeFeedRequest.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/request/GetMyRoomFeedRequest.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeProceedingInfoResponse.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🗒️ 챌린지 피드

#239 [Feature] 챌린지 관련 스케쥴러 추가
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeRepository.java
  Module-Domain/src/main/java/depromeet/domain/config/DomainConfig.java
  Module-Domain/src/main/java/depromeet/domain/config/SchedulingConfig.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: ✨ Feature

#240 [Feature] 챌린지 나가기 예외 케이스 처리
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/QuitChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/exception/CreatorCannotQuitException.java
  Module-API/src/main/java/depromeet/api/domain/mypage/exception/EndChallengeCannotQuitException.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/QuitChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
Labels: ✨ Feature, 🤠 마이페이지

#243 [Setting] 컨테이너 Timezone 설정
  Module-API/Dockerfile
Labels: ⚙ Setting

#246 [Feature] 챌린지 성공 기준 변경
  Module-Domain/src/main/java/depromeet/domain/config/BaseTime.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/test/java/depromeet/domain/userchallenge/domain/UserChallengeTest.java
Labels: ✨ Feature

#247 [Feature] 챌린지 탐색 DTO에 챌린지 상태 정보 필드 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/GetChallengeInfiniteScrollFeedUseCase.java
  Module-API/src/main/java/depromeet/api/util/ChallengeStatusUtil.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-API/src/test/java/depromeet/api/util/ChallengeStatusUtilTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/StatusType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeData.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeQueryRepository.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
Labels: ✨ Feature, ✅ Test, 🕵️ 챌린지 탐색

#250 [Feature] 챌린지 가입 시 상태값 수정
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Status.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#254 [Feature] 챌린지 가입 동시성 문제
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#261 [Refactor] 챌린지 테이블의 active 필드 수정
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/test/java/depromeet/api/domain/feed/controller/FeedControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ChallengeStatusType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeRepository.java
  Module-Domain/src/main/java/depromeet/domain/config/SchedulingConfig.java
Labels: 🔨 Refactor

#257 [Refactor] 이모지 응답 API 수정
  Module-API/src/main/java/depromeet/api/domain/emoji/controller/EmojiController.java
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/response/CreateEmojiResponse.java
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/response/DeleteEmojiResponse.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/CreateEmojiUseCase.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/DeleteEmojiUseCase.java
  Module-API/src/test/java/depromeet/api/domain/emoji/controller/EmojiControllerTest.java
Labels: 🔨 Refactor

#262 [Refactor] 챌린지 응답 DTO에서 카테고리 타입을 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
Labels: 🔨 Refactor

#263 [Feature] 상태 정보 enum값으로 변경에 따른 스케쥴링 작업
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/QuitChallengeUseCase.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/config/SchedulingConfig.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/test/java/depromeet/domain/userchallenge/domain/UserChallengeTest.java
Labels: ✨ Feature

#266 [Feature] 지출 상세보기에 이모지 response 추가
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
  Module-API/src/test/java/depromeet/api/domain/emoji/controller/EmojiControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/feed/controller/FeedControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/EmojiType.java
Labels: ✨ Feature, ✍️ 챌린지 기록

#267 [Refactor] 참여중인 챌린지 진행상태 enum으로 전달
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: 🔨 Refactor

#268 [Refactor] 챌린지 방 피드 첫 페이지 offsetRecordId null로 요청
  Module-API/src/main/java/depromeet/api/domain/feed/dto/request/GetChallengeFeedRequest.java
  Module-Domain/src/main/java/depromeet/domain/record/adaptor/RecordAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🗒️ 챌린지 피드

#270 [Docs] API 문서 작성
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateRandomNicknameResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/DateInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/HeadCountResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/ProfileResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/feed/ChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/feed/ChallengeInfiniteScrollResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/emoji/controller/EmojiController.java
Labels: 📃 Docs

#272 [Refactor] Enum 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/category/adaptor/CategoryAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/CategoryType.java
Labels: 🔨 Refactor

#274 [Refactor] 유저 챌린지 상태(WAITING) 추가에 따른 마이페이지 리팩토링
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetMyPageUseCase.java
Labels: 🔨 Refactor, 🤠 마이페이지

#278 [Refactor] 챌린지 나가기 challengeId 추가
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/QuitChallengeResponse.java
Labels: 🔨 Refactor

#279 [Feature] 챌린지 시작일자, 종료일자 유효성 검사
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/validator/CreateChallengeValidator.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/InvalidChallengeEndAtException.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/InvalidChallengeStartAtException.java
Labels: ✨ Feature, 🕵️ 챌린지 탐색

#280 [Refactor] 일부 API의 응답값 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/DeleteChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/DeleteChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/DeleteCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/UpdateCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/UpdateCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
Labels: 🔨 Refactor

#281 API 문서 최신화 및 배포
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/CreateRandomNicknameResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/DateInfoResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/DeleteChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/HeadCountResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/ProfileResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/feed/ChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/feed/ChallengeInfiniteScrollResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/DeleteChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/challenge/validator/CreateChallengeValidator.java
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/DeleteCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/UpdateCommentResponse.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/UpdateCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/emoji/controller/EmojiController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/QuitChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetMyPageUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/category/adaptor/CategoryAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/CategoryType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/InvalidChallengeEndAtException.java
  Module-Domain/src/main/java/depromeet/domain/challenge/exception/InvalidChallengeStartAtException.java
Labels: 🌏 Deploy

#285 [Fix] 챌린지 탐색 에러 해결
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ConditionFilter.java
Labels: 🐞 BugFix, 🕵️ 챌린지 탐색

#283 [Refactor] CORS 설정
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
Labels: 🔨 Refactor

#275 [Feature] 회원 탈퇴 구현
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/WithdrawalUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Profile.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Status.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/user/exception/AlreadyWithdrawalUserException.java
Labels: ✨ Feature, 🤠 마이페이지

#289 API 문서 최신화 및 배포
  Module-API/src/main/java/depromeet/api/config/security/SecurityConfig.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/WithdrawalUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ConditionFilter.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Profile.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/Status.java
  Module-Domain/src/main/java/depromeet/domain/user/domain/User.java
  Module-Domain/src/main/java/depromeet/domain/user/exception/AlreadyWithdrawalUserException.java
Labels: 🌏 Deploy

#294 [Refactor] 챌린지 탐색 API 리팩토링
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
Labels: 🔨 Refactor

#295 API 문서 최신화 및 배포
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/test/java/depromeet/domain/userchallenge/domain/UserChallengeTest.java
Labels: 🌏 Deploy

#291 [Feature] AWS S3 이미지 처리 최적화 - 리사이징 (+Lambda)
  Module-API/src/main/java/depromeet/api/config/s3/S3UploadPresignedUrlService.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/image/controller/ImageController.java
  Module-API/src/main/java/depromeet/api/domain/image/usecase/IssuePresignedUrlUseCase.java
  Module-API/src/test/java/depromeet/api/domain/image/controller/ImageControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/user/adaptor/UserAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#298 [Refactor] ChallengeStatusUtil 수정
  Module-API/src/main/java/depromeet/api/util/ChallengeStatusUtil.java
Labels: 🔨 Refactor

#297 [Refactor] 예외처리 - 종료된 챌린지에 대한 기록 생성, 수정, 삭제
  Module-API/src/main/java/depromeet/api/domain/image/usecase/IssuePresignedUrlUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/exception/InvalidChallengeStatusException.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/DeleteRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/validator/RecordValidator.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/user/adaptor/UserAdaptor.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#304 [Refactor] keyword 패키지 삭제
  Module-API/src/main/java/depromeet/api/domain/keyword/dto/KeywordsDto.java
Labels: 🔨 Refactor
