Repository depromeet/jalingobi-server, pull requests merged in 2023-07, with the labels that each got.

#317 [Feature] emoji 요청 DTO에서 유효성 검사 추가
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/request/CreateEmojiRequest.java
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/request/DeleteEmojiRequest.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/CreateEmojiUseCase.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/DeleteEmojiUseCase.java
  Module-API/src/test/java/depromeet/api/domain/emoji/controller/EmojiControllerTest.java
Labels: ✨ Feature

#312 [Refactor] 트랜잭션 중복 선언 제거
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/CreateCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetChallengeProceedingInfoUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyChallengeListUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/QuitChallengeUseCase.java
Labels: 🔨 Refactor

#319 [Refactor] 챌린지 기록 평가 항목 변경
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/request/CreateEmojiRequest.java
  Module-API/src/main/java/depromeet/api/domain/emoji/dto/request/DeleteEmojiRequest.java
  Module-API/src/main/java/depromeet/api/domain/emoji/usecase/DeleteEmojiUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/UpdateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/CreateRecordResponse.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/test/java/depromeet/api/domain/emoji/controller/EmojiControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/Emoji.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/EmojiType.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Evaluation.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
  Module-Domain/src/test/java/depromeet/domain/record/domain/RecordEvaluationTest.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#302 [Refactor] 챌린지 참가 시 요청이 null이면 기본 프로필 사용
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/JoinChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
Labels: 🔨 Refactor

#315 [Refactor] 댓글 CUD 리팩토링
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/CreateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/dto/request/UpdateCommentRequest.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/CreateCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/UpdateCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
Labels: 🔨 Refactor

#314 [Feature] 지출 기록 상세보기 평가 이모지 추가
  Module-API/src/main/java/depromeet/api/domain/record/dto/RecordInfo.java
Labels: ✨ Feature

#322 [Refactor] 마이페이지 조회에서 형 변환하는 부분 수정
  Module-API/src/main/java/depromeet/api/domain/image/dto/ImageFileExtension.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/response/GetMyPageResponse.java
  Module-API/src/main/java/depromeet/api/domain/mypage/mapper/MyPageMapper.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/GetMyPageUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/CreateRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/DeleteRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
Labels: 🔨 Refactor, 🤠 마이페이지

#323 [Feature] 토큰 재발급시 유효기간에 따라 갱신
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/response/TokenResponse.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/RefreshTokenUseCase.java
  Module-API/src/main/java/depromeet/api/util/CookieUtil.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
  Module-API/src/test/java/depromeet/api/domain/auth/controller/AuthControllerTest.java
Labels: 🔨 Refactor

#324 [Refactor] 컨트롤러 리팩토링
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/emoji/controller/EmojiController.java
  Module-API/src/main/java/depromeet/api/domain/feed/controller/FeedController.java
  Module-API/src/main/java/depromeet/api/domain/guest/controller/GuestController.java
  Module-API/src/main/java/depromeet/api/domain/image/controller/ImageController.java
  Module-API/src/main/java/depromeet/api/domain/jalingobi/controller/JalingobiController.java
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/domain/user/controller/UserController.java
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionHandler.java
  Module-Common/src/main/java/depromeet/common/response/CommonResponse.java
  Module-Common/src/main/java/depromeet/common/response/Response.java
  Module-Common/src/main/java/depromeet/common/response/ResponseService.java
Labels: 🔨 Refactor

#330 [Refactor] 챌린지 기록 삭제 시 S3 이미지 삭제하는 로직 추가
  Module-API/src/main/java/depromeet/api/domain/record/usecase/DeleteRecordUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#331 [Refactor] 성공 시 컨트롤러 응답값 형식 수정
  Module-API/src/main/java/depromeet/api/domain/mypage/controller/MyPageController.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
Labels: 🔨 Refactor

#301 [Refactor] 챌린지 탐색에서 컨트롤러단에 카테고리의 유효성 검증 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeFeedController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/GetChallengeInfiniteScrollFeedUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ChallengeSearchCondition.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ConditionFilter.java
Labels: 🔨 Refactor

#325 [Feature] 챌린지 가입 응답 DTO 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/JoinChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/JoinChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/JoinChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
Labels: ✨ Feature, ✅ Test

#329 [Feature] 챌린지 상세보기 시 상태를 수정
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/StatusType.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
Labels: ✨ Feature

#327 [Refactor] 챌린지 수정 리팩토링
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/UpdateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/UpdateChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/UpdateChallengeUseCase.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
Labels: 🔨 Refactor

#335 [Refactor] 챌린지 성공에서 누락 조건 추가
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeRepository.java
  Module-Domain/src/main/java/depromeet/domain/config/SchedulingConfig.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
Labels: 🔨 Refactor

#337 [Feature] Response result 값 null 일시 JsonInclude 로 설정
  Module-Common/src/main/java/depromeet/common/response/Response.java
Labels: ✨ Feature

#338 [Feature] swagger server url 설정
  Module-API/src/main/java/depromeet/api/config/SwaggerConfig.java
Labels: ✨ Feature, ⚙ Setting

#339 [Feature] 자린고비 기본 이미지 적용
  Module-Domain/src/main/resources/sql/jalingobi.sql
Labels: ✨ Feature

#343 API 모듈 배포
  Module-API/src/main/java/depromeet/api/config/SwaggerConfig.java
  Module-Common/src/main/java/depromeet/common/response/Response.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeRepository.java
  Module-Domain/src/main/java/depromeet/domain/config/SchedulingConfig.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/UserChallenge.java
  Module-Domain/src/main/resources/sql/jalingobi.sql
Labels: 🌏 Deploy

#342 [Refactor] 챌린지 종료 일자 유효성 검사 수정
  Module-API/src/main/java/depromeet/api/domain/challenge/validator/CreateChallengeValidator.java
Labels: 🔨 Refactor

#346 [Feature] 참여중인 챌린지에 인원 정보 추가
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyChallengeListResponse.java
  Module-API/src/test/java/depromeet/api/domain/feed/controller/FeedControllerTest.java
Labels: ✨ Feature

#352 [Fix] 피드 기록 불러오지 못하는 문제
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
Labels: 🐞 BugFix

#353 피드 조회 관련 버그 핫픽스
  Module-API/src/main/java/depromeet/api/domain/challenge/controller/ChallengeController.java
  Module-Domain/src/main/java/depromeet/domain/record/repository/RecordCustomRepositoryImpl.java
Labels: 🐞 BugFix

#355 [Feature] 피드 정보 추가
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
Labels: ✨ Feature, 🗒️ 챌린지 피드

#356 피드 정보 추가
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
Labels: 🌏 Deploy

#364 [Refactor] (프론트엔드 요구사항) httpOnly False로 변경
  Module-API/src/main/java/depromeet/api/util/CookieUtil.java
Labels: 🔨 Refactor

#365 [Refactor] (프론트엔드 요구사항) httpOnly False로 변경
  Module-API/src/main/java/depromeet/api/util/CookieUtil.java
Labels: 🌏 Deploy, ✅ Test

#367 [Refactor] 댓글 작성 API 응답값 수정
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/CreateCommentResponse.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
Labels: 🔨 Refactor

#368 댓글 등록을 위한 응답 정보 추가
  Module-API/src/main/java/depromeet/api/domain/comment/dto/response/CreateCommentResponse.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
Labels: 🌏 Deploy

#370 [Refactor] 마이페이지 응답 값 변수 변경
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Status.java
Labels: 🔨 Refactor, 🤠 마이페이지

#371 마이페이지 응답 값 변수 변경
  Module-API/src/test/java/depromeet/api/domain/mypage/controller/MyPageControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/userchallenge/domain/Status.java
Labels: 🌏 Deploy

#373 [Refactor] presigned url 발급 응답 값에 key 값 대신 image url
  Module-API/src/main/java/depromeet/api/domain/image/dto/response/IssuePresignedUrlResponse.java
  Module-API/src/main/java/depromeet/api/util/ImageUrlUtil.java
  Module-API/src/test/java/depromeet/api/domain/image/controller/ImageControllerTest.java
Labels: 🔨 Refactor

#374 presigned url 발급 응답값 변경
  Module-API/src/main/java/depromeet/api/domain/image/dto/response/IssuePresignedUrlResponse.java
  Module-API/src/main/java/depromeet/api/util/ImageUrlUtil.java
  Module-API/src/test/java/depromeet/api/domain/image/controller/ImageControllerTest.java
Labels: 🌏 Deploy

#379 [Bug] 마감임박, new 정보를 알 수 있는 데이터가 출력 안되는 문제 해결
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
Labels: 🐞 BugFix, 🤠 마이페이지

#381 챌린지 상태 태그 출력 안되는 문제 해결
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
Labels: 🌏 Deploy, 🐞 BugFix

#383 [Refactor] 챌린지 기록 content 필수 값 -> 선택 값으로 변경
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#388 [Refactor] 챌린지 지출 상세보기 Response 변경
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/QuitChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
Labels: ✨ Feature

#389 버전 최신화
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/DeleteCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/mypage/usecase/QuitChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
Labels: 🌏 Deploy

#391 [Hotfix] 댓글 생성, 삭제 에러 해결
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/CreateCommentUseCase.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
Labels: 🐞 BugFix

#393 [Bug] 챌린지 피드 selected null로만 응답
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/Emoji.java
Labels: 🐞 BugFix, 🗒️ 챌린지 피드

#394 서버 에러 해결
  Module-API/src/main/java/depromeet/api/domain/comment/controller/CommentController.java
  Module-API/src/main/java/depromeet/api/domain/comment/usecase/CreateCommentUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/test/java/depromeet/api/domain/comment/controller/CommentControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/comment/adaptor/CommentAdaptor.java
  Module-Domain/src/main/java/depromeet/domain/comment/domain/Comment.java
  Module-Domain/src/main/java/depromeet/domain/emoji/domain/Emoji.java
Labels: 🌏 Deploy, 🐞 BugFix

#396 [Refactor] 챌린지 상세보기 응답 DTO에 필드 추가
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/ProfileResponse.java
Labels: 🔨 Refactor

#398 [Bug] 내 방 피드에서 이모지 selected 값 설정 문제
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/mapper/RecordListMapper.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
Labels: 🐞 BugFix, 🗒️ 챌린지 피드

#397 [Refactor] 챌린지 기록 시 response 데이터 삭제하기
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/CreateRecordResponse.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
Labels: 🔨 Refactor, ✍️ 챌린지 기록

#399 업데이트 사항 반영
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/ProfileResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/EmojiInfo.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetChallengeFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/response/GetMyRoomFeedResponse.java
  Module-API/src/main/java/depromeet/api/domain/feed/mapper/RecordListMapper.java
  Module-API/src/main/java/depromeet/api/domain/feed/usecase/GetMyRoomFeedUseCase.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/CreateRecordResponse.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/response/GetRecordResponse.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
Labels: 🌏 Deploy

#400 [Feature] 챌린지 생성 시 기본 이미지 설정
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-API/src/test/java/depromeet/api/util/ChallengeStatusUtilTest.java
  Module-Domain/build.gradle
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/CategoryType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/DefaultImageProperties.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/FoodDetailType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Image.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ThumbImageProperties.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeData.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
Labels: ✨ Feature

#403 [Feature] 챌린지 피드 기록에 challengeId 추가
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
Labels: ✨ Feature

#404 업데이트 반영
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/request/CreateChallengeRequest.java
  Module-API/src/main/java/depromeet/api/domain/challenge/dto/response/GetChallengeResponse.java
  Module-API/src/main/java/depromeet/api/domain/challenge/mapper/ChallengeMapper.java
  Module-API/src/main/java/depromeet/api/domain/challenge/usecase/CreateChallengeUseCase.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ChallengeFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/MyFeed.java
  Module-API/src/main/java/depromeet/api/domain/feed/dto/ParticipatedChallenge.java
  Module-API/src/main/java/depromeet/api/domain/mypage/dto/MyPageUserChallenge.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeControllerTest.java
  Module-API/src/test/java/depromeet/api/domain/challenge/controller/ChallengeFeedControllerTest.java
  Module-API/src/test/java/depromeet/api/util/ChallengeStatusUtilTest.java
  Module-Domain/build.gradle
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/CategoryType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/DefaultImageProperties.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/FoodDetailType.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Image.java
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/ThumbImageProperties.java
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeData.java
  Module-Domain/src/test/java/depromeet/domain/challenge/domain/ChallengeTest.java
  Module-Domain/src/test/java/depromeet/domain/record/adaptor/RecordAdaptorTest.java
Labels: 🌏 Deploy

#406 [Refactor] 챌린지 탐색 응답 DTO 수정
  Module-Domain/src/main/java/depromeet/domain/challenge/repository/ChallengeData.java
Labels: 🔨 Refactor

#409 [Bug] 이모지 삭제 기능 해결
  Module-Common/src/main/java/depromeet/common/exception/CustomExceptionStatus.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
  Module-Domain/src/main/java/depromeet/domain/record/exception/NoMatchEmojiException.java
Labels: 🐞 BugFix

#411 [Hotfix] 이모지 등록 문제 해결
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
Labels: 🐞 BugFix

#415 [Hotfix] 챌린지 참가 검증 문제 해결
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
Labels: 🐞 BugFix

#418 [Bug] evaluation null 허용
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/UpdateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Evaluation.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
Labels: 🐞 BugFix

#419 업데이트 반영
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/UpdateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Evaluation.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Record.java
Labels: 🌏 Deploy

#421 [Bug] enum 타입 null 문제 해결
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/CreateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/dto/request/UpdateRecordRequest.java
  Module-API/src/main/java/depromeet/api/domain/record/mapper/RecordMapper.java
  Module-API/src/main/java/depromeet/api/domain/record/usecase/UpdateRecordUseCase.java
  Module-API/src/test/java/depromeet/api/domain/record/controller/RecordControllerTest.java
  Module-Domain/src/main/java/depromeet/domain/record/domain/Evaluation.java
Labels: 🐞 BugFix

#423 [Docs] README.md 업데이트
  README.md
Labels: 📃 Docs

#425 [Temp] 테스트를 위한 설정 변경
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
Labels: ✨ Feature

#426 시연용 업데이트 반영
  Module-Domain/src/main/java/depromeet/domain/challenge/domain/Challenge.java
  README.md
Labels: 🌏 Deploy
