Repository depromeet/jalingobi-server, pull requests merged in 2023-05, with the labels that each got.

#3 [Build] Github Actions를 이용한 CI 빌드, 테스트 자동화
  .github/workflows/ci.yml
  .gitignore
  Module-API/src/main/java/depromeet/HelloController.java
  Module-API/src/test/java/depromeet/HelloControllerTest.java
Labels: ⚙ Setting

#6 [Style] Spotless(코드 포멧팅) 적용
  .github/workflows/ci.yml
  Module-API/src/main/java/depromeet/HelloController.java
  Module-API/src/main/java/depromeet/ModuleApiApplication.java
  Module-API/src/main/java/depromeet/config/SwaggerConfig.java
  Module-API/src/main/java/depromeet/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/domain/auth/service/LoginUseCase.java
  Module-API/src/test/java/depromeet/HelloControllerTest.java
  Module-API/src/test/java/depromeet/ModuleApiApplicationTests.java
  Module-Domain/src/main/java/depromeet/ModuleModuleApplication.java
  Module-Domain/src/main/java/depromeet/user/domain/User.java
  Module-Domain/src/main/java/depromeet/user/service/LoginService.java
  build.gradle
Labels: ⚙ Setting

#8 [Test] Jacoco 적용하고, Codecov로 테스트 커버리지 관리하기
  .github/workflows/ci.yml
  build.gradle
Labels: ✅ Test

#12 [Setting] 개발 생산성 향상을 위한 Git Hooks 설정
  build.gradle
  scripts/pre-commit
Labels: ⚙ Setting

#19 [Setting] 테스트 세팅 및 환경별 profile 설정을 위한 변수 추가
  Module-API/Dockerfile
  Module-API/build.gradle
  Module-API/src/main/java/depromeet/ModuleApiApplication.java
  Module-Common/build.gradle
  Module-Common/src/main/java/depromeet/CommonApplication.java
  Module-Common/src/main/java/depromeet/ModuleCommonApplication.java
  Module-Common/src/test/java/depromeet/CommonApplicationTests.java
  Module-Domain/build.gradle
  Module-Domain/src/main/java/depromeet/ModuleDomainApplication.java
  Module-Domain/src/main/java/depromeet/ModuleModuleApplication.java
  Module-Domain/src/main/java/depromeet/user/domain/User.java
  build.gradle
  docker-compose.yml
Labels: ⚙ Setting

#26 [Bug] github action 에서 submodule yml 파일 복사하지 못하는 문제 해결
  .github/workflows/api-cd.yml
Labels: 🐞 BugFix

#39 [Feature] Refresh Token으로 Access Token을 재발급받는 reissue 추가
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/service/AuthService.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
Labels: ✨ Feature, 🙋‍♀️ 유저

#40 [Refactor] 설정 파일 위치 조정
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/TokenInfo.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/request/KakaoAuthRequest.java
  Module-API/src/main/java/depromeet/api/domain/auth/dto/response/KakaoAuthResponse.java
  Module-API/src/main/java/depromeet/api/domain/auth/exception/InvalidJwtException.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/KakaoAuthUseCase.java
  Module-API/src/main/java/depromeet/api/domain/auth/validator/OAuthValidator.java
  Module-API/src/main/java/depromeet/api/domain/record/controller/RecordController.java
  Module-API/src/main/java/depromeet/api/util/AuthenticationUtil.java
  Module-API/src/main/java/depromeet/api/util/JwtUtil.java
Labels: 🔨 Refactor

#45 [Refactor] AuthService를 헥사고날 아키텍처 패턴에 맞게 리팩토링
  Module-API/src/main/java/depromeet/api/domain/auth/controller/AuthController.java
  Module-API/src/main/java/depromeet/api/domain/auth/usecase/AuthUseCase.java
  Module-API/src/test/java/depromeet/api/controller/AuthControllerTest.java
  Module-API/src/test/java/depromeet/api/controller/HelloControllerTest.java
Labels: 🔨 Refactor, 🙋‍♀️ 유저
